### PR TITLE
Added new provider

### PR DESCRIPTION
**Pull request by sympact06**

### CODE REVIEW

**Comment by sympact06** [comment]
https://github.com/SocialiteProviders/Providers/pull/1192

**Review by atymic — APPROVED** [review]

**Comment by atymic** [comment]
Actually its not in alpha order, can you fix the sort?

**Comment by sympact06** [comment]
> Actually its not in alpha order, can you fix the sort?

How would I fix that? Normally its default in alpha order right?

**Comment by atymic** [comment]
As in provider starting with R should be before provider starting with V

**Review by atymic — APPROVED** [review]

**Comment by atymic** [comment]
Actually seems there is a syntax error 
Screen Shot 2024-10-17 at 12 01 11@2x

**Comment by sympact06** [comment]
@atymic Ready for review

**Comment by atymic** [comment]
Build still seems to be erroring.

**Comment by sympact06** [comment]
Fixed @atymic

**Pull request closed without merging**
